### ISSUE TITLE
Add password verification field in sign up page.

### ISSUE THREAD

**Issue by Abhey** [ContriHUB/ContriHub-18#10]
Currently, the user enters only once his password while signup. 

Add one more password field and check if the password provided in both of them is same or not. Only if they are same allow the user to signup otherwise show an error message stating that the passwords do not match.

**Comment by yashbhutoria** [comment]
I would like to contribute to this one.

**Comment by Vishal1541** [comment]
@Abhey I'd like to take this issue :smiley:

**Comment by suraj-goel** [comment]
Assign this task to me.
I am ready to solve this issue

**Comment by Abhey** [comment]
@suraj-goel You have been assigned this issue. You have 2 days to work on this. Failing to resolution of this issue within the time frame will lead to it's assignment to another participant.

**Comment by jarvisdev** [comment]
sir, please assign this issue to me.
