### ISSUE TITLE
points transparency

### ISSUE THREAD

**Issue by dbads** [ContriHUB/ContriHub-18#117]
add two attributes bonus_points and deducted_points in profile model to store bonus/deducted_points in user profile for transparency of all points :smile: 

Also modify the response_pr view to store bonus and deducted points in user profile at the time of verification.

**Comment by jarvisdev** [comment]
What about the PRs that are verified? Do we have to calculate for them also?

**Comment by dbads** [comment]
no that can't be done :smile: just do it for new prs

**Comment by dbads** [comment]
> What about the PRs that are verified? Do we have to calculate for them also?

yeah, actually this can be done :smile: but that's one time thing. you can ignore this
