### ISSUE TITLE
Functionality to delete submitted PR

### ISSUE THREAD

**Issue by Abhey** [ContriHUB/ContriHub-18#13]
Currently, the user can only submit Pull Requests for verification. Although in UI user is provided with an option to delete submitted Pull Request but the functionality is not supported by the backend.

Add the logic in the backend so that the user can also delete submitted Pull Requests.

**Comment by ashwini571** [comment]
Sir assign this to me

**Comment by dbads** [comment]
@ashwini571 this issue has been assigned to you.

**Comment by jarvisdev** [comment]
please assign this issue to me, sir. I have done it for an individual profile page. Every user can delete their pr from their profile page.

**Comment by dbads** [comment]
What's issue?

**Comment by jarvisdev** [comment]
functionality to delete the submitted pr in user profile page.

**Comment by dbads** [comment]
Okay fine.. yiu just create an issue for that, solve it and create pr : smile: you will get extra points for finding bug
