### ISSUE TITLE
separate css from html code

### ISSUE THREAD

**Issue by dbads** [ContriHUB/ContriHub-18#19]
You have to simply make a new css file and put the css code on any one html page to this new css file and then include that css file in html file. e.g Projects/templates/Projects/home.html has some css at head section. put it in a different css file and include it in head again.

You have to do this just for any one html page. :smile: 
Mention the name of html page while making prs?

No need to ask for permissions just Mention the page name which isn't already mentioned and start working on it. :smile:

**Comment by dbads** [comment]
Name the css files accordingly.

**Comment by harryandriyan** [comment]
I'll take it

**Comment by dbads** [comment]
@harryandriyan its yours. Create a request on contrihubs.herokuapp.com for getting points too :smile:

**Comment by rochelleilustre** [comment]
next please :)

**Comment by debodirno** [comment]
@dbads can i take it too?

**Comment by dbads** [comment]
@debodirno  @rochelleilustre  @harryandriyan anybody can take it, just make sure you guys don't work on same page/thing :smile: and also create request on https://contrihubs.herokuapp.com for achieving points and making place on leaderboard.

**Comment by debodirno** [comment]
Will work on home.html.

**Comment by gemul** [comment]
i do the profile.html

**Comment by agoiabel** [comment]
Are there still pages to work on ?

**Comment by AzDan** [comment]
I'm doing on the home.html page.

**Comment by su050300** [comment]
Can i take it
