### ISSUE TITLE
notify user when their PR is verified 

### ISSUE THREAD

**Issue by dbads** [ContriHUB/ContriHub-18#48]
Currently there is a notification via email to mentors when any user requests for verification for any of their(mentor's) Issue. see Projects/views.py>request_pr function.

You have to implement same kind of notification Email for users when their PR's are verified by mentors.
modify Projects/views.py>response_pr function to send email to users when their PR is verified or rejected.

You are going to enjoy this one :smile:

**Comment by spencercorwin** [comment]
Hi @dbads - I'm working on this. It seems fairly simple. But I'm having trouble seeing where the response_pr function is used. Also, I want to know the structure of the request parameter being passed into the response_pr function. I'm about to submit a pull request anyway with what I think it is you are looking for. I also cleaned up some of the grammar and phrasing of the messages.
