### ISSUE TITLE
Add forgot password functionality

### ISSUE THREAD

**Issue by Abhey** [ContriHUB/ContriHub-18#9]
Currently, the user can't recover his password once he/she forgets it. Add the functionality by which a user can recover his password. 

As the username in our case is same as GitHub username you can use GitHub API's to fetch user email address and send a password recovery mail to that user.

You are free to explore other mechanisms for password recovery.

**Comment by Apoorva-13** [comment]
can I try this?

**Comment by rht6226** [comment]
Assign this issue to me.

**Comment by dbads** [comment]
@rht6226 yeah you can do it. Ask if need some help 😄 also gui should be followed the current app theme

**Comment by rht6226** [comment]
Github is showing Deployment error for some reason.

**Comment by dbads** [comment]
@rht6226 you can also test app locally? No need to deploy :smile:

**Comment by rht6226** [comment]
@dbads  sir I did checked it locally. It is working perfectly. Now, If you can check the pull request and see if there is any problem.
