### ISSUE TITLE
error: issues are not being filtered according to project name and mentor name

### ISSUE THREAD

**Issue by jarvisdev** [ContriHUB/ContriHub-18#95]
There is a big problem with issues filtering. It is only filtering issues correctly when they are being filtered according to their difficulty level.
When we try to filter issues according to mentor or project name it is showing all the issues.
Filtering issues is not working.

**Comment by jarvisdev** [comment]
I want to self-assign this to me, please. :smile:

**Comment by dbads** [comment]
Yeah.. And this issue appeared after adding difficulty based filter added by you itself :smile: I kinda couldn't see the bug. Here this PR has code for infinite scroll on leaderboard page, create pr for that too. FOr this issue you'll get some points :smile:

**Comment by jarvisdev** [comment]
sir for infinite scroll on leader board I have created a pr #98
