### ISSUE TITLE
upvote and downvote feature for issues

### ISSUE THREAD

**Issue by dbads** [ContriHUB/ContriHub-18#97]
Add a button to upvote or downvote issues.
on clicking upvote button upvote count should increase by 1 if not already upvoted else it should decrease. Same for downvote.

**Comment by dbads** [comment]
@ashwini there can be many ways of doing this, but here you have to build as mentioned in issue description. 
i.e both upvote and downvote are independent. you can either increase/decrease upvote/downvote.

**Comment by dbads** [comment]
> The two buttons are indeed independent but the issue i've discussed above will be more user friendly if implemented

actually you have done perfect :smile: I kinda just misunderstood.

**Comment by dbads** [comment]
Pr link can be submitted, its working :smile:

**Comment by ashwini571** [comment]
Sir seriously it can't.  I suffered the same issue while submitting PR for 'Fetching through Ajax' problem.And that too is not working till date

**Comment by dbads** [comment]
whats error? did you check console results?

**Comment by dbads** [comment]
I tried creating a pr request from a user account and it works? others are also creating request :smile: 
I am not sure whats bug?

**Comment by ashwini571** [comment]
Submitted finally......but still wondering what the hell was that problem🤔

**Comment by dbads** [comment]
Actually there is something unusual.. but not sure what?  fix that if you find it :smile:
